### PR TITLE
Update for parachain / integration tests

### PR DESCRIPTION
**Pull request by benoitdevos**
### Migrate to parachain
* Update client, client-node and node-api.
* Use `CollectionParams` and `ValidAccountId`.

logion-network/logion-internal#1228

### Add integration tests
* 4 integrations tests are added, testing both CSV creation and import (validation is tested indirectly within import)
* 2 new options are added, companion of `--local`: `--creativeCommonsLoc` and `--logionClassificationLoc`. These 2 options are reserved for testing locally (development/testing) and are just ignored when passing using `--env`.

#### Open issues
The SignAndSendStrategy had to be adapted to:
```ts
class IntegrationTestSignAndSendStrategy implements SignAndSendStrategy {

    canUnsub(result: ISubmittableResult): boolean {
        return result.isCompleted;
    }
}
```
Otherwise I get very very often `NotFound` or `WrongCollectionLoc`.

logion-network/logion-internal#1114

### CODE REVIEW

**Review by gdethier — APPROVED** [review]
Good job! I would just check that 1) we can publish the images in the repo without any license and 2) we need to have 10 images published instead of 2-3.

**Comment by gdethier** [comment]
...and also, I would love to learn a bit more about `isCompleted`.

**Comment by benoitdevos** [comment]
> Good job! I would just check that 1) we can publish the images in the repo without any license and 2) we need to have 10 images published instead of 2-3.

I have amended the commit with other images.

**Comment by benoitdevos** [comment]
> ...and also, I would love to learn a bit more about `isCompleted`.

As discussed, I will investigate. But I can already confirm that integration tests are much more stable on my side - no failure yet after 4 runs - with this new setup.

**Pull request merged**
